#!/usr/bin/env bash
# build_alpine.sh

# build configuration file, see README for the variables it should define
if [ -e ".build-config" ]; then
   source ".build-config"
fi

# check if the texlive-medium container has been set up
if [ -z "$(buildah images | grep "texlive-medium")" ]; then
    # if not, create an empty alpine container
    ctr=$(buildah from alpine)
    mnt=$(buildah mount $ctr)
    brunch="buildah run $ctr /bin/sh -c"

    # install base packages
    $brunch 'apk add make wget perl tar gzip git'

    # get and unpack the texlive installer
    if [ -e ".build-config" ]; then
        cp "${TEXLIVE_INST}" "$mnt/home/"
    else
        $brunch \
            "wget \
\"http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz\" \
-O home/install-tl-unx.tar.gz"
    fi

    $brunch "cd home; tar -xf install-tl-unx.tar.gz"

    # directory into which the installer was unpacked
    texlivedir=$($brunch "cd home; tar --exclude='*/*' -tf install-tl-unx.tar.gz")

    # copy the install profile into the unpacked directory
    cp texlive.profile "${mnt}/home/${texlivedir}"

    if [ -e ".build-config" ]; then
        # make the mountpoint for the local CTAN mirror
        mkdir "${mnt}/home/texlive-local"
        mount --bind "${CTANDIR}" "${mnt}/home/texlive-local"
    fi

    $brunch "cd home/${texlivedir}; ./install-tl $REPO_FLAG \
-profile=texlive.profile"

    $brunch "rm -rf home/${texlivedir}"

    if [ -e ".build-config" ]; then
        # unmount the local CTAN mirror
        umount "${mnt}/home/texlive-local"
    fi

    # commit the new container and remove it
    buildah commit $ctr containers-storage:texlive-medium
    buildah umount $ctr
    buildah rm $ctr
fi

# create an texlive-medium container
ctr=$(buildah from texlive-medium)
mnt=$(buildah mount $ctr)
brunch="buildah run $ctr /bin/sh -c"

if [ -e ".build-config" ]; then
    mount --bind "${CTANDIR}" "${mnt}/home/texlive-local"
    git clone -l --no-hardlinks ./ "${mnt}/home/texstyle"
else
    $brunch "git clone https://gitlab.com/QuantumAnon/TexStyle.git \
--branch develop \
/home/texstyle"
fi

$brunch "tlmgr install $REPO_FLAG lipsum bbm bbm-macros mdframed zref needspace enumitem"
$brunch "cd /home/texstyle; ./configure"
$brunch "cd /home/texstyle; make docs"
# echo "here's the log boss"
# echo "================================================================================"
# $brunch "cat /home/texstyle/src/texstyle/out/texstyle.log"
# echo "================================================================================"

if [ -e ".build-config" ]; then
    umount "${mnt}/home/texlive-local"
fi

buildah umount $ctr
buildah rm $ctr
