\ProvidesClass{Default.cls}

\RequirePackage{TexStyle}

%--------------------------------------------------
% Document Settings

  % Paragraph sizing
    \setlength{\parskip}{1.5\baselineskip}
    \setlength{\parindent}{5pt}

  % Link design
    \hypersetup
    {
      colorlinks=true,
      linkcolor=blue,
      filecolor=magenta,
      urlcolor=cyan,
    }
    \urlstyle{same}

    
%--------------------------------------------------
